image: maven:3.8.7-eclipse-temurin-17-focal

stages:
  - install
  - package

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

.deploy:
  stage: package
  before_script:
    - echo "$GITLAB_ROOT_CA" > /usr/local/share/ca-certificates/gitlab.myusine.fr.pem
    - update-ca-certificates
    - >
      keytool 
      -import 
      -trustcacerts
      -storepass changeit 
      -noprompt
      -alias my-gitlab 
      -file /usr/local/share/ca-certificates/gitlab.myusine.fr.pem 
      -keystore "$JAVA_HOME/lib/security/cacerts"
  tags:
    - myusine
  script:
    - mvn deploy -s ci_settings.xml

install:
  stage: install
  tags: [myusine]
  script:
    - mvn clean install
  artifacts:
    expire_in: "10 minutes"
    paths: 
      - .m2/repository/com/example/rest-service-complete/0.0.1-SNAPSHOT/rest-service-complete-0.0.1-SNAPSHOT.war

upload:
  stage: package
  tags: [myusine]
  script:
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" 
      --upload-file .m2/repository/com/example/rest-service-complete/0.0.1-SNAPSHOT/rest-service-complete-0.0.1-SNAPSHOT.war
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/rest-service-complete-0.0.1.war"
  
  