image: maven:3.8.7-eclipse-temurin-17-focal

stages:
  - package

deploy:
  stage: package
  before_script:
    - echo "$GITLAB_ROOT_CA" > /usr/local/share/ca-certificates/gitlab.myusine.fr.pem
    - update-ca-certificates
    - >
      keytool 
      -import 
      -trustcacerts
      -storepass changeit 
      -noprompt
      -alias my-gitlab 
      -file /usr/local/share/ca-certificates/gitlab.myusine.fr.pem 
      -keystore "$JAVA_HOME/lib/security/cacerts"
  tags:
    - myusine
  script:
    - echo "OK"
    # - mvn deploy -s ci_settings.xml
  